### ISSUE TITLE
中文蝌蚪单/双引号似乎是没在表里？

### ISSUE THREAD

**Issue by cailurus** [huntzhan/text-cleaner#1]
蝌蚪双引号：“  和 ”，以及蝌蚪单引号：‘ 和 ’

**Comment by huntzhan** [comment]
可以提供一个 case 吗？

Sent from myMail for iOS

Monday, 3 October 2016, 16:02 +0800 from Jinyang Zhou  notifications@github.com:

**Comment by cailurus** [comment]
``` python
>>> print remove('《箭士柳白猿》8月映，张艺谋羡慕“新武侠片”', [CHINESE_SYMBOLS_AND_PUNCTUATION, SYMBOLS_AND_PUNCTUATION_EXTENSION, SYMBOLS_AND_PUNCTUATION])

>>> 箭士柳白猿 8月映 张艺谋羡慕“新武侠片”
```

蝌蚪双引号分别是 \u201c 和 \u201d，我 grep 了一下，[general punctuation](https://en.wikipedia.org/wiki/General_Punctuation) 似乎是都没在表里。

**Comment by huntzhan** [comment]
谢谢，回去我修一下，的确没有包含 general punctuation range

http://apps.timwhitlock.info/unicode/inspect?s=“#block-U2000

Sent from myMail for iOS

Monday, 3 October 2016, 16:43 +0800 from Jinyang Zhou  notifications@github.com:
